[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm i -g corepack@latest && corepack enable && corepack prepare pnpm@10.22.0 --activate", "CI=true pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node index.js"

